# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b912cc3adbd2030195064cc26744baea"
name = "vault"
application_url = "https://khusan.ngrok.io"
embedded = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "customers/update" ]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks"

[app_proxy]
url = "https://husan-server.ngrok.io/api/proxy"
subpath = "vault"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_customers,read_orders,write_customers,read_themes,write_discounts"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://husan-server.ngrok.io/auth/callback" ]
