import type { StyleTokens, ThemePreset } from '../types/display-config.types';

export const PRESETS: Record<ThemePreset, StyleTokens> = {
  rounded: {
    cardBorderRadius: '16px',
    cardShadow: '0 10px 20px -16px rgba(15, 23, 42, 0.4)',
    cardBackground: '#fff',
    cardBorderColor: '#e2e8f0',
    cardHoverShadow: '0 8px 24px rgba(0, 0, 0, 0.08)',
    cardHoverLift: '-2px',
    cardImageAspectRatio: '3/4',
    cardInfoPadding: '12px 16px',
    cardTitleSize: '14px',
    cardTitleColor: '#0f172a',
    cardPriceSize: '14px',
    cardPriceColor: '#0f172a',
    cardButtonBg: '#0f172a',
    cardButtonColor: '#fff',
    cardButtonRadius: '8px',
    gridGap: '24px',
    gridMobileGap: '12px',
    pageMaxWidth: '1200px',
    pagePadding: '40px 20px',
    headerSpacing: '40px',
    titleSize: '28px',
    titleColor: '#18181b',
    subtitleSize: '16px',
    subtitleColor: '#6b7280',
    notifBorderRadius: '12px',
    notifFontSize: '14px',
    notifButtonRadius: '6px',
    timerBorderRadius: '10px',
    timerNumSize: '28px',
    titleWeight: '600',
    subtitleWeight: '400',
    cardTitleWeight: '500',
    cardPriceWeight: '600',
  },
  sharp: {
    cardBorderRadius: '4px',
    cardShadow: '0 1px 3px rgba(0, 0, 0, 0.1)',
    cardBackground: '#fff',
    cardBorderColor: '#d1d5db',
    cardHoverShadow: '0 2px 6px rgba(0, 0, 0, 0.12)',
    cardHoverLift: '-1px',
    cardImageAspectRatio: '1/1',
    cardInfoPadding: '10px 12px',
    cardTitleSize: '13px',
    cardTitleColor: '#111827',
    cardPriceSize: '13px',
    cardPriceColor: '#111827',
    cardButtonBg: '#111827',
    cardButtonColor: '#fff',
    cardButtonRadius: '2px',
    gridGap: '16px',
    gridMobileGap: '8px',
    pageMaxWidth: '1200px',
    pagePadding: '32px 16px',
    headerSpacing: '32px',
    titleSize: '24px',
    titleColor: '#111827',
    subtitleSize: '14px',
    subtitleColor: '#6b7280',
    notifBorderRadius: '4px',
    notifFontSize: '13px',
    notifButtonRadius: '2px',
    timerBorderRadius: '4px',
    timerNumSize: '24px',
    titleWeight: '700',
    subtitleWeight: '400',
    cardTitleWeight: '600',
    cardPriceWeight: '700',
  },
  soft: {
    cardBorderRadius: '24px',
    cardShadow: '0 4px 24px rgba(0, 0, 0, 0.06)',
    cardBackground: '#fff',
    cardBorderColor: '#f1f5f9',
    cardHoverShadow: '0 8px 32px rgba(0, 0, 0, 0.06)',
    cardHoverLift: '-3px',
    cardImageAspectRatio: '3/4',
    cardInfoPadding: '16px 20px',
    cardTitleSize: '15px',
    cardTitleColor: '#1e293b',
    cardPriceSize: '15px',
    cardPriceColor: '#1e293b',
    cardButtonBg: '#1e293b',
    cardButtonColor: '#fff',
    cardButtonRadius: '999px',
    gridGap: '32px',
    gridMobileGap: '16px',
    pageMaxWidth: '1200px',
    pagePadding: '48px 24px',
    headerSpacing: '48px',
    titleSize: '32px',
    titleColor: '#1e293b',
    subtitleSize: '18px',
    subtitleColor: '#94a3b8',
    notifBorderRadius: '20px',
    notifFontSize: '15px',
    notifButtonRadius: '999px',
    timerBorderRadius: '16px',
    timerNumSize: '32px',
    titleWeight: '500',
    subtitleWeight: '400',
    cardTitleWeight: '500',
    cardPriceWeight: '500',
  },
  minimal: {
    cardBorderRadius: '0px',
    cardShadow: 'none',
    cardBackground: 'transparent',
    cardBorderColor: '#e5e7eb',
    cardHoverShadow: '0 1px 3px rgba(0, 0, 0, 0.08)',
    cardHoverLift: '0px',
    cardImageAspectRatio: '4/5',
    cardInfoPadding: '8px 0',
    cardTitleSize: '14px',
    cardTitleColor: '#18181b',
    cardPriceSize: '14px',
    cardPriceColor: '#18181b',
    cardButtonBg: '#18181b',
    cardButtonColor: '#fff',
    cardButtonRadius: '0px',
    gridGap: '20px',
    gridMobileGap: '12px',
    pageMaxWidth: '1200px',
    pagePadding: '40px 20px',
    headerSpacing: '40px',
    titleSize: '28px',
    titleColor: '#18181b',
    subtitleSize: '16px',
    subtitleColor: '#6b7280',
    notifBorderRadius: '0px',
    notifFontSize: '14px',
    notifButtonRadius: '0px',
    timerBorderRadius: '0px',
    timerNumSize: '28px',
    titleWeight: '400',
    subtitleWeight: '400',
    cardTitleWeight: '400',
    cardPriceWeight: '500',
  },
};
